############################# Base configuration #############################
baseURL = "https://unicef.github.io/inventory/"
title = "UNICEF O.S. Inventory"
theme = "inventory"
enableEmoji = true
enableGitInfo = true

# Google Analytics
googleAnalytics = "G-80FMX4TPM0"

# Allow unsafe HTML
[markup.goldmark.renderer]
unsafe = true


############################# Navigation #############################
[[menu.main]]
weight = 10
name = "FAQ"
url = "faq"

[[menu.main]]
weight = 20
name = "pages"
url = "pages"
hasChildren = true

    [[menu.main]]
    parent = "pages"
    name = "Communities"
    url = "communities"
    weight = 10

	[[menu.main]]
	parent = "pages"
	name = "Data Ethics & Transparency"
	url = "data"
	weight = 20

    [[menu.main]]
    parent = "pages"
    name = "Design"
    url = "design"
    weight = 30

    [[menu.main]]
    parent = "pages"
    name = "Developer Tools & Automation"
    url = "dev-tools"
    weight = 40

    [[menu.main]]
    parent = "pages"
    name = "Documentation"
    url = "documentation"
    weight = 50

    [[menu.main]]
    parent = "pages"
    name = "Governance"
    url = "governance"
    weight = 60

    [[menu.main]]
    parent = "pages"
    name = "Legal & Policy"
    url = "legal-policy"
    weight = 70

    [[menu.main]]
    parent = "pages"
    name = "Meta"
    url = "meta"
    weight = 80

    [[menu.main]]
    parent = "pages"
    name = "Missions"
    url = "missions"
    weight = 90

    [[menu.main]]
    parent = "pages"
    name = "Open Hardware"
    url = "hardware"
    weight = 100

    [[menu.main]]
    parent = "pages"
    name = "Project Management"
    url = "project-management"
    weight = 110

    [[menu.main]]
    parent = "pages"
    name = "Reproducibility"
    url = "reproducibility"
    weight = 120

    [[menu.main]]
    parent = "pages"
    name = "Sustainability"
    url = "sustainability"
    weight = 130


############################# Default parameters #############################
[params]
# Need to replace with SVG logo
#logo = "favicon.ico"

# OpenGraph / Twitter Card metadata
description = "UNICEF Open Source Inventory. A UNICEF Global Innovation knowledge base of best practices and resources for working and leading Open."
author = "Justin W. Flory, UNICEF Office of Innovation, and others"
image = "images/UNI309823.jpg"

# customize color
primary_color = "#00BDF2"
body_color = "#e0e4e8"
text_color = "#636363"
text_color_dark = "#003E5D"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family (choose from https://fonts.google.com/)
font_family = "Open+Sans"

# contact form action (works with https://formspree.io)
contact_form_action = "#"

# related article number limit
article_count = 3


############################# Social links #############################
# themify icon pack : https://themify.me/themify-icons

[[params.social]]
icon = "ti-github"
name = "UNICEF Open Source Inventory on GitHub"
link = "https://github.com/unicef/inventory"

[[params.social]]
icon = "ti-twitter"
name = "@UNICEFinnovate on Twitter"
link = "https://twitter.com/UNICEFinnovate"


############################# Markup tweaks and customization #############################
[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = 'murphy'
tabWidth = 4

[markup.asciidocExt]
preserveTOC = true
sectionNumbers = true

############################# Related Articles #############################
[taxonomies]
  category = "categories"


#######################################################################################
#                             Multilingual configurations                             #
#######################################################################################

############################# English #############################
[Languages.en]
languageName = "en"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "Creative Commons BY-SA 4.0"

# banner
[Languages.en.params.banner]
title = "UNICEF Open Source Inventory"
subtitle = "A UNICEF Global Innovation knowledge base of best practices and resources for working and leading Open."
bg_image = "images/banner.jpg"
placeholder = "Have a question? Search the site here."


############################# Español / Spanish #############################
[Languages.es]
languageName = "es"
languageCode = "es-mx"
weight = 2
home = "Página principal"
copyright = "Creative Commons BY-SA 4.0"

# banner
[Languages.es.params.banner]
title = "Inventario de Open Source de UNICEF"
subtitle = "Una base de conocimientos de innovación mundial del UNICEF sobre mejores prácticas y recursos para trabajar y dirigir Open."
bg_image = "images/banner.jpg"
placeholder = "¿Tienes una pregunta? Busque en el sitio aquí."
